# Generated by Django 4.1.1 on 2022-09-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_food_remove_order_food_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.IntegerField(default=2),
        ),
    ]
