# Generated by Django 4.1.1 on 2022-09-21 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_table_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='percent',
        ),
        migrations.AddField(
            model_name='totalsum',
            name='percent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.percent'),
        ),
    ]
