# Generated by Django 4.1.1 on 2022-09-21 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_percent_remove_order_percent_totalsum_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalsum',
            name='percent',
        ),
        migrations.AddField(
            model_name='order',
            name='percent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.percent'),
        ),
    ]
