# Generated by Django 4.1.1 on 2022-09-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_remove_totalsum_percent_order_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='percent',
        ),
        migrations.DeleteModel(
            name='TotalSum',
        ),
    ]
